name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm --filter server prisma generate

      - name: Run backend tests
        run: pnpm --filter server test

      - name: Run e2e tests
        run: pnpm e2e
