name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        working-directory: server
        run: pnpm dotenv -e .env.test -- pnpm prisma generate

      - name: Migrate test database
        working-directory: server
        run: pnpm dotenv -e .env.test -- pnpm prisma migrate deploy

      - name: Seed test database
        working-directory: server
        run: pnpm dotenv -e .env.test -- pnpm prisma db seed

      - name: Run backend tests
        working-directory: server
        run: pnpm test

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: pnpm e2e

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          if-no-files-found: ignore
          retention-days: 7
