name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        working-directory: server
        run: pnpm prisma generate

      - name: Migrate test database
        working-directory: server
        run: dotenv -e .env.test -- pnpm prisma migrate deploy

      - name: Run backend tests
        working-directory: server
        run: pnpm test
